apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-eks-app
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - devops-app

  selector:
    matchLabels:
      app: devops-eks-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
